// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA45qTufz4cQDe_qVQpJwJQ3SXi54lc_v0',
    appId: '1:480072514557:web:9b322682c942aafc16b794',
    messagingSenderId: '480072514557',
    projectId: 'funeraria-renacer',
    authDomain: 'funeraria-renacer.firebaseapp.com',
    storageBucket: 'funeraria-renacer.appspot.com',
    measurementId: 'G-NQZC05C4N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFaFUdXI1Fz2Cnehok6x9_nCtw4gtwlpg',
    appId: '1:480072514557:android:6153187410203b1516b794',
    messagingSenderId: '480072514557',
    projectId: 'funeraria-renacer',
    storageBucket: 'funeraria-renacer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9-m4uBgMbKSdkJA3gicTbQKhd051zsDg',
    appId: '1:480072514557:ios:6bc7351c38fb09e416b794',
    messagingSenderId: '480072514557',
    projectId: 'funeraria-renacer',
    storageBucket: 'funeraria-renacer.appspot.com',
    iosBundleId: 'com.example.funerariaRenacer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9-m4uBgMbKSdkJA3gicTbQKhd051zsDg',
    appId: '1:480072514557:ios:5501d0a10c03a05016b794',
    messagingSenderId: '480072514557',
    projectId: 'funeraria-renacer',
    storageBucket: 'funeraria-renacer.appspot.com',
    iosBundleId: 'com.example.funerariaRenacer.RunnerTests',
  );
}
